- hosts: dbservers
  # user: root
  tasks:
    - name: Install and create Oracle database 19c
      import_role:
        name: dbsoftware19c_install
      when: "ansible_facts['os_family'] == 'RedHat'"
#  roles:
#   - dbsoftware19c_install
