- hosts: dbservers
  # user: root
  tasks:
    - name: Install and create Oracle database 19c
      import_role:
        name: install
      when: "ansible_facts['os_family'] == 'RedHat'"
#  roles:
#   - install
